[licenses]
unlicensed = "deny"
allow = ["MIT", "Apache-2.0", "BSD-3-Clause", "ISC", "Unicode-DFS-2016"]

[advisories]
vulnerabilities = "deny"
unmaintained = "warn"
ignore = []

[bans]
multiple-versions = "warn"