# deny.toml
[graph]
all-features = false

[advisories]
vulnerability = "all"
unmaintained = "transitive"
yanked = "all"
notice = "warn"

[licenses]
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
]

[bans]
multiple-versions = "warn"